import { SiteFooter } from "../components/SiteFooter.tsx";
import { SiteHeader } from "../components/SiteHeader.tsx";
import type { LegalBlock, LegalDocument } from "../data/legal/types.ts";
import { Link, NavLink } from "react-router-dom";
import { HOME_PATH, PRIVACY_PATH, QUOTE_LINK, TERMS_PATH } from "../lib/routes.ts";

const GENERATOR_URL = "https://app-privacy-policy-generator.nisrulz.com/";

function Block({ block }: { block: LegalBlock }) {
  if (typeof block === "string") return <p>{block}</p>;
  return (
    <ul>
      {block.map((item) => (
        <li key={item}>{item}</li>
      ))}
    </ul>
  );
}

interface LegalPageProps {
  document: LegalDocument;
}

/** Renders a policy document (privacy policy or terms) as a standalone page. */
export function LegalPage({ document }: LegalPageProps) {
  return (
    <>
      <SiteHeader brandHref={HOME_PATH}>
        <Link className="ghost" to={QUOTE_LINK}>
          Back to enquiries
        </Link>
      </SiteHeader>
      <main className="wrap privacy-page">
        <article className="privacy-text">
          <div className="kicker">Legal</div>
          <h1>{document.title}</h1>
          {document.intro.map((block, index) => (
            <Block key={index} block={block} />
          ))}
          {document.sections.map(({ heading, blocks }) => (
            <section key={heading}>
              <h2>{heading}</h2>
              {blocks.map((block, index) => (
                <Block key={index} block={block} />
              ))}
            </section>
          ))}
          <p className="updated">
            This {document.title} page was generated by <a href={GENERATOR_URL}>App Privacy Policy Generator</a>.
          </p>
          <p>
            <Link to={QUOTE_LINK}>Return to the enquiry forms</Link>
          </p>
        </article>
      </main>
      <SiteFooter>
        <Link to={HOME_PATH}>Home</Link>
        <NavLink to={PRIVACY_PATH}>Privacy policy</NavLink>
        <NavLink to={TERMS_PATH}>Terms &amp; Conditions</NavLink>
      </SiteFooter>
    </>
  );
}
