import { SiteFooter } from "../components/SiteFooter.tsx";
import { SiteHeader } from "../components/SiteHeader.tsx";
import type { LegalBlock, LegalDocument } from "../data/legal/types.ts";
import { PRIVACY_HASH, TERMS_HASH } from "../lib/routes.ts";

const GENERATOR_URL = "https://app-privacy-policy-generator.nisrulz.com/";

function Block({ block }: { block: LegalBlock }) {
  if (typeof block === "string") return <p>{block}</p>;
  return (
    <ul>
      {block.map((item) => (
        <li key={item}>{item}</li>
      ))}
    </ul>
  );
}

interface LegalPageProps {
  document: LegalDocument;
  /** The hash this page is served at, used to mark its footer link as current. */
  hash: string;
}

/** Renders a policy document (privacy policy or terms) as a standalone page. */
export function LegalPage({ document, hash }: LegalPageProps) {
  const current = (link: string) => (link === hash ? "page" : undefined);
  return (
    <>
      <SiteHeader brandHref="#">
        <a className="ghost" href="#quote">
          Back to enquiries
        </a>
      </SiteHeader>
      <main className="wrap privacy-page">
        <article className="privacy-text">
          <div className="kicker">Legal</div>
          <h1>{document.title}</h1>
          {document.intro.map((block, index) => (
            <Block key={index} block={block} />
          ))}
          {document.sections.map(({ heading, blocks }) => (
            <section key={heading}>
              <h2>{heading}</h2>
              {blocks.map((block, index) => (
                <Block key={index} block={block} />
              ))}
            </section>
          ))}
          <p className="updated">
            This {document.title} page was generated by <a href={GENERATOR_URL}>App Privacy Policy Generator</a>.
          </p>
          <p>
            <a href="#quote">Return to the enquiry forms</a>
          </p>
        </article>
      </main>
      <SiteFooter>
        <a href="#">Home</a>
        <a href={PRIVACY_HASH} aria-current={current(PRIVACY_HASH)}>
          Privacy policy
        </a>
        <a href={TERMS_HASH} aria-current={current(TERMS_HASH)}>
          Terms &amp; Conditions
        </a>
      </SiteFooter>
    </>
  );
}
